- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Added the basic repository setup with a simple `vimrc` and `bashrc`
> Basic Repository Setup

- rc/bashrc
- rc/vimrc
Provide a generic bash and vimrc for engineers
Provide an example for a basic bash and vim setup. Users can then customize each as they see fit
Documented through comments in `rc` files
> ENH: RC files

- scripts/pkg_release
- scripts/pydev_register
```
pkg_release pmgr R1.0.2
```
Clones the repo and creates a `R1.0.2` directory in the current directory. Does reasonable error checking. Primarily for things that have not been given conda-recipe support yet.
Nolan did this manually today, it should be scripted.
I tested it and various error cases
It hasn't
> Add package release script for pcdshub

- scripts/pcds_conda
`source pcds_conda` -> get the latest environment
Include environment variable to set and change the behavior:
```
export PCDS_CONDA_VER=1.0.0
source pcds_conda
```
This shouldn't live in a random directory, it should be one of the tools.
Manually
Hasn't
> ENH: Add sourceable pcds_conda environment

- scripts/pyps-deploy
Nifty python script to fill out the `pyps/apps/<app-name>` release folders for things that are in the github/conda ecosystem.
There were a lot of steps and automating them allowed me to improve the end result.
I did lots of testing
eh
> Add pyps-deploy script

- scripts/ami_offline_psana
cxi_1 -> cxi_0
timetoolbdb -> timetoolbdb
> use main cxi cnf file, fix filename for timetool plugin

- rc/bashrc
- scripts/ami_offline_psana
- scripts/epicsArchChecker
- scripts/restartdaq
A little bit a cleanup of epicsArchChecker following #103. There is one big commit that is just capitalization changes that unfortunately makes this file a bit harder to review, sorry.
One line removed from ami_offline_psana from my [comment](https://github.com/pcdshub/engineering_tools/pull/100#discussion_r799206263) in #100.
I also could have sworn we decided to use `latest-released` as opposed to `latest` for engineering_tools. Did we change our minds at some point? This PR changes it but we can take that out if there was some reason.
Lastly, this fixes the `-m` option for restartdaq, which allows you to specify a different machine to run the daq on. This option has been around forever but I'm not sure that it ever worked. This fix makes it work but if it's not desired, we should just …
> MNT: Cleanup of a few files

- scripts/makepeds
- scripts/makepeds_psana
title is a decent short description
add the -U option for the UXI. 
because makepeds should work for all detectors
testing makepeds for the uxi locally
not really.
> makepeds for uxi

- scripts/ipmConfigEpics
Updating PVs to reflect name changes to the ioc @ZryletTC 's request.
PVs were outdated and no longer applicable
Tested by running the script and opening screens.
Nowhere
> MNT: Changing PVs from SC1:BMMON to USR:DIO

- README.md
- scripts/detector_totals.py
Add a script/report for the detector group. The report generates event count by detector type.
> Event count by detector type

- scripts/new_bare_repo
The last elif statement was executing oppositely to what was intended. Replacing [ with the [[ operator fixed the issue.
> Added extra bracket to fix issue with last elif statement

- scripts/makepeds_psana
We will move to a new offline/FFB computing setup when data taking starts again. We will still need to process pedestals runs.
run jungfrau4M & epix10k2M jobs in S3DF and psana.
> changes to run makepeds also in s3df

- scripts/makepeds
- scripts/makepeds_psana
Make makepeds compatible with running on the S3DF, without changing the well established workflow
Tested locally S3DF for data on the FFB.
Need more test for data on S3DF, from hutch opr accounts and with data in transfer
Docstrings in scripts
> Pedestals on S3DF

- scripts/wherepsana
wherepsana creates a temporary file... this should be in /tmp, not in the current directory tmp.
> wherepsana typo: tmp should be /tmp

- scripts/makepeds
- scripts/takepeds
Makepeds to work on S3DF in interactive mode.
With xcsx1004322 run 16
N/A
> default to s3df even if no queue is passed

- scripts/archive-details
- scripts/archive-details.py
Adds an additional script for checking details of a PV through the archiver URL request interface. 
I wanted some more information while debugging something in the archiver, and found that there is a BPL available that dumps many details about a PV. 
This has been tested interactively with a live PV in the archiver. 
The code and this PR.
> archive-details - Add in a script for checking more details about archived PVs

- README.md
- scripts/getAllEvrFWVersions
- scripts/getAllTprFWVersions
Adds scripts that poll found EVRs or TPRs for their firmware version, as reported via the IOC. 
We've had some recent updates to EVR and TPR hardware and firmware. These scripts will help figure out what needs to be updated. 
Tested from psbuild. 
This PR. 
Example EVR script output: 
Example TPR script output:
> Add scripts to get EVR and TPR firmware versions

- scripts/makepeds
- scripts/makepeds_psana
- scripts/makepeds_psana2
split makepeds for LCLS1 and LCLS2
add archon support
test/fix epix100 LCLS2 handling
improve error reporting by the script
makepeds should also work for all LCLS2 detectors that need if
It should also return helpful error messages when possible.
re-processe pedestals for selected LCLS1 and LCLS2 experiment/run/detector combos
> makepeds for LCLS2

- scripts/camViewer
Add the option to start kfe as -H (hutch), if you are not on kfe-console it will start a ssh connection.
Please test, for me it's working in my account and rixopr.
```
camViewer -H kfe
HUTCH: kfe
Not in SSH, connecting to kfe-console...
===============================================================================
NOTICE TO USERS
This is a Federal computer system and is the property of the United States
Government. It is for authorized use only. Users (authorized or unauthorized)
have no explicit or implicit expectation of privacy.
Any or all uses of this system and all files on this system may be intercepted,
monitored, recorded, copied, audited, inspected, and disclosed to authorized
site, Department of Energy, and law enforcement personnel, as well as
authorized officials of other …
```
> add kfe with ssh option

- scripts/makepeds_psana
- scripts/makepeds_psana2
Split calibration jobs in cycles _and_ segments
Also spellcheck suggestion
> shellcheck fixes & running code in segments&calibcycle

- scripts/ipmConfigEpics
Add mfx dg1 wavev3 while keeping shellcheck in place
> Add dg1 wave8 v3

- scripts/makepeds
add MFX to list of LCLS2 hutches for makepeds.
> MFX is also a LCLS2 hutch for makepeds

- scripts/makepeds_psana2
re-add modified check, return codes not used, also also will not yet work
> mods to jungfrau lcls2 carib

- .github/CODEOWNERS
Remove the granular codeowners in favor of the special @pcdshub/engtools-team 
To ensure that changes to critical system scripts get reviewed by the people most likely to understand how much testing needs to be done prior to merge
N/a
N/a, but I'll announce in the ecs slac channel later
> MNT: switch to special engineering tools team

- scripts/checkcnf
- scripts/daq_utils.py
- scripts/takepeds
Restore deleted #295
@silkenelson
> MFX is treated as LCLS2 instrument & cleanup

- scripts/imgr
- scripts/iocmanager
It works this time, I swear
It didn't work because I dropped the auto-discovered HUTCH
Interactively for txi
> FIX: iocmanager again
