scripts/pydev_env
scripts/pydev_register

- `pydev_env` can be sourced to activate the most recent conda release, with your checked-out packages masking the release packages using `$PYTHONPATH`
- `pydev_register` can be used to add modules and scripts to this path via creating softlinks in your home area
These are also reasonable starting points for making your own scripts to point to your own conda environments instead of the shared environment.
Helpful for rapidly setting up dev environments separate from the main environments. The workflow is something like:
- check out modules
- `pydev_register path_to_module module`
- `pydev_register path_to_script bin`
- `source pydev_env`
- `python run_tests.py`
Later, you decide that you want to remove packages from this dev path:
- `rm ~/pydev/packagename`
I've found that this workflow …

ENH: Add helper scripts for hutch-python development environments

---

scripts/pydev_env

I noticed this was hardlinked to the old script

FIX: Redirect pydev_env to the new pcds_conda setup script

---

scripts/pcds_conda

- Use command instead of bin
- Use /usr/bin/env bash instead of /bin/bash
Removing corner cases where commands may be installed in different places on different machines. The `command` built-in ignores the user's alias, which is important for consistent script behavior between users.
I tested most of the previous fail cases
- Works on `cxi-control`
- Works with Bruce's `ls -F` alias

FIX: use command instead of /bin

---

scripts/get_info

Hi, I changed the first method for --gethutch/getHutch to use the IP address subnet.  I made this a PR because I first wanted to check with the hutch/daq POCs that this is acceptable and because I'd like representatives to help me populate the dictionary `hutch_subnets` with whatever IP subnets they'd want to associate with their hutches!
Using the hostname or working directory doesn't always work so using the IP address seemed more reliable.  
Tested on XCS/CXI control room machines by calling ./get_info --getHutch

Changed get_info to first try finding hutch by IP address subnet

---

scripts/motor-expert-screen

- Cut the `.whatever` out of the PV name
- Avoid annoying error message when xdotool isn't available
- Annoying to do `motor-expert-screen XPP:USR:MMS:01.RBV` and getting fail when script should be smarter
- Annoying to see error message
Opened motor screens of all types (old, current, xps8)

ENH: motor-expert-screen accepts .RBV now

---

scripts/BLmotors

**Description**
Creation of a new script that checks the IMS motors configuration in the parameter manager.
**Motivation and Context**
This script helps the engineers and scientists to know if the IMS motors' configuration status.
The script will generate a report for:
1. Motors with no configuration.
2. Motors with configurations that have values different.
from the configured.
3. Motors are not found.
4. Full report with all the motors and their status (If they have configuration assigned if that configuration matches or not with the configured values,  and if the motors are not found).
**How Has This Been Tested?**
The script was tested in the hutches XPP, CXI, MFX, MEC, XCS. The parameter manager was also another resource to check if the information generated by the script is …

DEV: Add Beamline motors Report Script

---

scripts/makepeds
scripts/makepeds_psana

Use the new calibration commands for the Jungfrau & fix epix10k pedestals to work on FFB
Not much more details needed.
The epix10k pedestals should be processable on the FFB as the data is available (potentially a lot) faster.
The Jungfrau pedestals should use the new scripts. This also allows to process calibration cycles in parallel and deploys a other files that currently need to be added by hand.
test from development directory on a number of runs, using both interactive& queue modes both on psana and psffb.
Not really.

various changes to pedestals

---

scripts/makepeds_psana

fix validity string option in code 
fix logic to quit (or not) when errors on submitted jobs are found
add additional check for failed epix10k pedestal jobs (note: now depend on underlying code keeping this printout)

small fixes, notably to epix10k jobs.

---

scripts/ami_offline_psana

What the title said - make ami_offline work in many more cases
MEC also uses jet
use cxi_0.cnf to figure out pathss
only time tool plugin
use the new FFB as patch
the old version just did not work right.
tried to open a few different experiments on psana
nowhere.

mec uses jet, cxi_0.cnf as cxi cnf file for path, only tt plugin

---

scripts/epicsArchChecker

epicsArchChecker
-detault to show only warnings, only status is optional.
-deal with the addition of ca/pva in the LCLS2 epicsArch files to properly find duplicates
for LCLS-2, the status check currently does not do what is needed (most likely). It also makes the script run longer as it does not just read files, but actually connects to PVs.
adding the ca/pva designation for the LCLS2 epicsArch files broke the comparison
We would like to roll this out to TMO...
by running the script on the TMO epicsArch file.

EpicsArchChecker (LCLS2) fixes

---

scripts/imgr
scripts/iocmanager

- Add imgr
- Change iocmanager to bypass the IocManager bash script in the IocManager package
The bash scripts to access imgr and iocmanager should exist in one place only and engineering_tools is a convenient place because it houses many other commonly used scripts and is already on most peoples's PATHs. This is the first step in moving the scripts from the iocmanager package to engineering_tools. After all hutches have adopted a new release of engineering_tools containing these scripts, I will remove the no-longer-useful bash scripts from the iocmanager package.
Interactively.
Shellcheck passes with only SC1091 messages.
Commented each section in both scripts.

Add imgr and merge iocmanager into one bash file

---

scripts/pydev_register

Added a check in the if statement that verifies the module to be registered exists.
pydev_register will currently happily allow you to register modules that don't exist.
Closes #62 
This was tested by running the script with a module that exist and does not exist and checking to see what shows up in ~/pydev

ENH: check that the path exists when registering a module/bin

---

README.md
scripts/takepeds

Used  `get_info --getstation` to get the current station.
Added a usage function.
It automatically gets the station for the user as opposed to the default station 0 before.
Tested on cxi-daq and cxi-monitor and it works fine.
Added a usage fucntion in the script

ENH: Changed the takepeds to automatically pick a station

---

scripts/makepeds_psana

Moving from no-longer existing scripts to the 'new' XTCAV setup:
https://confluence.slac.stanford.edu/display/PSDM/New+XTCAV+Documentation
the old method to use makepeds for the XTCAV did no longer work.
by running the scripts 'locally' and using the queue
Not really. It just fixes a couple of available options to actually work.

use new XTCAV scripts for dark&lasingOff processing

---

scripts/makepeds
scripts/makepeds_psana

- Moved the makepeds-specific flags to the top of the help, just so I could see that this matches makepeds_psana.
- Created a hutch-specific configuration file /reg/g/pcds/pyps/config/$HUTCH/makepeds.cfg, which contains the ADUMAX, ADUMIN, NOISESIGMAX, and NOISESIGMIN settings for each class of detector.  For now, this only exists in xpp.
- Removed the -g geometry flag.  Instead, added a bash function "deploy_geometry" that will see if the geometry directory exists already, and if not call the geometry_deploy_constants script to deploy the geometry automatically.  This is also given an optional command that will be run as well if we need to deploy geometry.
- Call deploy_geometry for cspad, epix10k, jungfrau, and rayonix detectors.  In the event of a jungfrau, also call …

Added hutch-specific configfile, changed to use geometry_deploy_constants

---

scripts/ipmConfigEpics

In the script, ipmConfigEpics I changed the sc1ipm to usrdio in the three instances it appears in. This was per Tyler's request to make the names more intuitive. 
https://jira.slac.stanford.edu/browse/LCLSECSD-1131
I ran the command using the change in variable name and got the same results.

in ipmConfigEpics changed instances of sc1ipm to usrdio

---

scripts/makepeds
scripts/makepeds_psana

Fix geometry deployment in makepeds
Now the geometry is automatically deployed for the relevant detectors. The geometry deployment has been moved at the end of the pedestal processing, so that relevant folders are created.
Add ffb queue 4 to ffb queue list
`./makepeds -u espov -r 2 -q ffbh4q`
os xppopr for xpplz0020
N/A

ENH: now geometry deploy by default for relevant detectors

---

scripts/makepeds_psana

same changes as for geometry to deal with more verbose output of calibfile.
Also fix bug introduced when trying to add DRPSRCF support
This script needs to deploy the epix100 gains in run 21!
By running the command....

FIX: makepeds: changed needed for geometry also needed for gain

---

scripts/motor-expert-screen

Add the right expert screen for SmarAct stages
Have the expert screen script open the right screen for SmarAct
Tested with some axis of the LIB SmarAct IOC at XPP.
Docstring in the script

ENH/Add SmarAct MSC2 to motor-expert-screen

---

scripts/dev_conda
scripts/pcds_conda

Check if the server has a problem before switching the renderer library.
This is WIP because it is messy and littered with echo and I'm not sure if it's even fully right.
Setting the `__GLX_VENDOR_LIBRARY_NAME` didn't work for all consoles.
For many cases it actually created a problem rather than solving it.
Only do it if we definitely fail without it.
That is, when:
- glxinfo has a nonzero exit code (usually 0 is success, 1 is errors, 139 is segfault)
- glxinfo has a 0 exit code but shows errors in the text (TODO: does this actually happen or is it a remnant of an older version of the script?)
Heavily interactively.
N/A

FIX: pcds_conda, dev_conda: only set mesa if renderer is failing

---

scripts/pydev_env

Unset the long `PYDM_DISPLAYS_PATH` from `pcds_conda` in the `pydev_env` setup
The path here was masking personal dev env screens with the production screens, preventing testing of dev typhos templates when using `pydev_env`.
Interactively only
Release notes later

FIX: pydev_env was not showing dev typhos templates

---

scripts/dev_conda
scripts/pcds_conda

- For `dev_conda`, use the latest tag as a base instead of an arbitrary outdated `dev` environment. This gives us a better chance of dev always being up-to-date and stable.
- For `pcds_conda` and `dev_conda`, find the latest tag via config file instead of automatically.
The outdated `dev` environment is causing issues because the base packages are so far behind and it's not possible to update it safely in-place.
The dynamically picked `pcds_conda` environment path causes issues (closes #136)
Now, we will be able to test and vet the fully installed environment before dropping people into it by default.
I've placed the config file for this inside of the conda environment itself. This keeps it one level hidden from accidental changes and allows a different config seamlessly when we boost to …

MAINT: cleaner handling of latest conda and dev conda

---

scripts/makepeds_psana

makepeds declares success after calling the geometry or gain deployment scripts.  This should be conditional on the return code of the script.
Declaring failure if the script fails is much less confusing.

Check for failure before declaring success.

---

scripts/motor-expert-screen

Added a check for Beckhoff motors and launch the typhos motor screen. 
Previously, Beckhoff motors defaulted to the Aerotech edm screen.
Tested the script by calling IMS motors and PLC motors. Ensured that the typhos window title iscorrectly defined so the repositioning works as intended.
Added comments where the check is performed.

ENH: Added check for Beckhoff axis

---

scripts/makepeds_psana

Updates required for new psana1 release
-Added ":dir=" divider to commands running in drpsrcf
-Changed calibrun argument "--thr_rms"  to "--thr_rms_max"
New psana1 
Tested by running "./makepeds -u jortiz -F -q ffbh3q -r 1" for experiment xcsx1001121.
This run includes two Epix100a and an Epix10ka2m detector
deploy_constants is currently not handling directories correctly and will be updated in the next release.

MNT: Updates required for new psana1 release

---

scripts/new_bare_repo

There are a lot of IOCs that are not properly version controlled since we moved from svn to git. Often, I run into IOCs that do not have a hutch specific bare repo setup, so I made this script to help facilitate the process of creating that bare repo and the subsequent steps afterwards.
This script: 
1. Initializes the local repository
2. Checks in the .cfg file, Makefile and .gitignore
3. Creates the bare repo in the proper location using eco_tools git-bare-repo script
4. Sets this newly created bare repo as the remote origin and sets it as the upstream
As mentioned above
This has been tested once with the Smarpod IOC, which I had yet to create a hutch bare repo for. Worked perfectly. 
Code includes simple explanations for how to use the script.
If this script is redundant, or could be …

Bare repo script

---

scripts/wherepsana

Added the PID to the temporary file name to hopefully avoid collisions should two people be running the script at once.
The old version of the script only tested a few possible event mask values, the largest being 16, which didn't seem to be correct anyway.  The detail part of the script has been rewritten to really test the values in the event mask, and also complain if the mask contains any values *not* supported by an event process.

Fully test the event masks and fix temp file name

---

README.md
scripts/ioctool

Changes to ioctool script involved making searching through config files better, adding the option to open other useful iocInfo files, allowing camera name input to find information, addition of a "cat" option and fixed issues that dealt with multiple iocs.
Fixes #79 .
Tests involved sourcing the script from my epics-dev directory using various camera, pv and ioc names.
Both scripts have updated usage functions

Changes to ioctool

---

scripts/takepeds

remove the .py extension on the elog script call, as per the recent changes to pcds_conda

fix takepeds for elog script

---

scripts/camViewer

Fix hutch auto-discovery in camViewer
The auto-discoevry had been accidentaly removed in the previous PR on this script
Tested as xppopr on xpp-control for the following commands:
camViewer
camViewer -H xpp
camViewer -H xll

(re)add hutch autodiscovery

---

scripts/makepeds
scripts/takepeds

As we are now using the S3DF, takepeds and makepeds should only run from there, or the calib files won't be written to the right place. Removing old psana and ffb from it ensures that there won't be accidental run of makepeds on the wrong systems. Should older pedestal be reprocessed, one should run from a previous release of engineering_tools
Full workflow tested with the Jungfrau from xpp-control
Self documented with docstring

clean up psana / ffb stuff from makepeds

---

README.md
scripts/hdf5_to_gif.py
scripts/image-saver.py

I don't know what happened on the original pull request. I believe I accidentally pulled on my rix-gifs branch instead of master or rebased improperly and duplicated Vincent's commits. I wanted to revert but ended up closing the pull request in the process. Going to try again with a new request. hdf5_to_gif.py has not changed. I changed the readme entry for image-saver to reflect the gui changes I made. The changes in image-saver are mainly in button_gui, based on feedback from future users. They are turning the button green while images are being taken, being able to change the number of images to take from within the gui, and being able to change the text on each button (they start as just the name on the camera). There are also minor changes to main and take_images which involve …

Adding scripts to take camera images and convert saved hdf5 files to gifs

---

README.md
scripts/set_gem_timing

Adding what should be a temporary hack script but may be somewhat long lived to provide a one line mechanism for operators to switch the timing paradigm on the HXR-GEM. This script:
- Sets PV: `KFE:CAM:TPR:02:MODE` to either SC or NC
- Invokes `imgr` to set the GEMs IOC version to the correct version for the corresponding timing paradigm
Invokation once sourced is of form: `set_gem_timing [scheme]` 
Schemes besides `NC` and `SC` will be rejected.
Associated PR: https://github.com/pcdshub/IocManager/pull/9
The `set_gem_timing` bash script critically:
- Sets PV: `KFE:CAM:TPR:02:MODE` to either SC or NC
- Invokes `imgr` to set the GEMs IOC version to the correct version for the corresponding timing paradigm
- Input validates that only 1 argument is supplied and that argument is either `SC` …

feat(set_gem_timing): allowing operators to switch between HXR-GEM SC and NC timing with a one line script

---

scripts/set_gem_timing

Addressing the valid concern in the set_gem_timing script that we want to guard against the edge case where PV: `KFE:CAM:TPR:02:MODE` is inconsistent with IOC software path.
For reference here is the intended pairing:
|KFE:CAM:TPR:02:MODE Value | IOC Software Path|
| -------- | ------- |
| SC | `ioc/fee/GasDetDAQ/R4.0.22-NOTS`    |
| NC | `ioc/fee/GasDetDAQ/R4.0.22`     |
Critical functional change is that if an operator tries to run `set_gem_timing` into a mode in which the PV: `KFE:CAM:TPR:02:MODE` already is in it **will not** terminate the program.
https://github.com/pcdshub/engineering_tools/pull/163#discussion_r1320381287
Code comment and output of command

fix(set_gem_timing): updated logic to reflect application layer concers: do not exit the program if PV and IOC software are out of sync

---

scripts/makepeds_psana

- Currently, `makepeds` waits until jobs complete, checking every 10 seconds, but does not indicate the job status (pending/running/etc). This PR provides feedback on the status of those submitted jobs so a decision can be made as to whether it's just a matter of waiting patiently or requesting additional resources (etc.).
- Currently, most portions of `makepeds` exclude the recorder datastream; however, the `calibrun` portion does not. This PR excludes the recorder data stream from this latter part as well.
- `Ctrl-c` can now be used to cancel all SLURM jobs. This allows early exit if jobs are stuck pending and a new strategy is needed.
- Exits `makepeds` early if `sbatch` fails and provides a hint to a common cause (account doesn't have permission on experiment).
- Provides additional …

[ENH] Additional `makepeds` reporting and exclusion of recorder data stream

---

README.md
scripts/kinit_helper

Adds two functions kauth and afsauth, which will create kerberos and afs tokens respectively. afsauth will call kauth. afsauth is called if the script is run, functions are accessible by sourcing. 
#147 
shellcheck, running the script, and sourcing and trying functions individually and checking that tokens are created with klist and tokens or that correct error message is printed.
Code is commented

Kinit helper

---

scripts/evrStatus

evrStatus now uses a pydm screen to display timing information. Additionally, the list of evr pvs has been updated to remove defunct pvs and add new ones.
https://jira.slac.stanford.edu/browse/ECS-1023
shellcheck and launching the screen by specifying the hutch, pvs via command line arguments, and by entering manually using the -evr flag.
to_display comment has been updated

evrStatus pydm 

---

scripts/motor-expert-screen

Adds a check in motor-expert-screen to see if the stage is encoded, and bring up the correct screen.
This script is heavily used by the beamline scientists, and they need to have access to the right PVs. 
Tested interactively with a stage.

ENH: Add check for SmarAct encoder

---

scripts/dev_conda
scripts/pcds_conda

PyDM has an environment variable, `PYDM_DEFAULT_PROTOCOL`, that allows you to set a default protocol to use.
This PR sets the default protocol to `ca` (channel access (EPICS)), which is the most used protocol, allowing us to omit it when building out our screens. This also makes the conversion from edm to pydm smoother.
When setting up a pydm channel, you're expected to provide a protocol in the form of a pseudo-url:
```
ca://MY:PVNAME
```
If, instead, you just use:
```
MY:PVNAME
```
You'll get the following error:
```
Channel MY:PVNAME did not specify a valid protocol and no default protocol is defined. This channel will receive no data. To specify a default protocol, set the PYDM_DEFAULT_PROTOCOL environment variable.
```
Setting this environment variable helped @patoppermann 's screen …

ENH: set the default pydm protocol to ca, the most-used protocol

---

scripts/makepeds
scripts/makepeds_psana

Makepeds should only run on S3DF now.
Clean up old system processing
Run from an xpp exp with Jungfrau det

Remove non-s3df pedestal processing

---

scripts/camViewer

Added a condition to the elseif for UED
Because CamViewer was not running for UED  (https://jira.slac.stanford.edu/browse/LCLSECSD-2108?filter=-2)
Running the command
Not needed

Adding default camera for UED

---

scripts/archive-resume

Adds in a script for resuming PVs in the archiver from the command line. 
TMO found a PV that was paused in the archiver and the people online at the time did not know how to fix it. The _did_ know how to check the status using `archive-status`, so I thought perhaps a similar bash tool would be helpful in the future. 
https://slac.slack.com/archives/CUC9NLU8H/p1712197816806739
Tested live using a PV in the FTL. Paused the pv manually from the archiver web interface.

Add in new script for resuming PVs in the archiver.

---

.flake8
.github/workflows/standard.yml
.pre-commit-config.yaml
.shellcheckrc
scripts/BLmotors
scripts/detector_totals.py
scripts/elog_par_post
scripts/epicsArchChecker
scripts/epix_gains
scripts/evrStatus
scripts/get_info.py
scripts/hdf5_to_gif.py
scripts/image_saver
scripts/pfeiffer_serial_tools/address_change.py
scripts/pfeiffer_serial_tools/control.py
scripts/pyps-deploy
scripts/questionnaire_tools
scripts/xpp_update_happi_line.py

- adds pre-commit hooks and relevant .rc files to the repository
- adds github actions pre-commit job to run on pull requests
- (WIP) apply changes suggested by pre-commit (flake8, shellcheck, etc)
~- [ ] bash scripts (hooooo boy)~
- Converts some old py2 scripts to py3
The style is whack.
Shellcheck is a much larger effort, and one that we should be careful with.  We'll have to go through those more carefully, but for now the CI will only check diff'd files
I spent way too much time trying to grab specific sha's for pre-commit's `--from-ref` and `--to-ref` arguments, but the location of that information in the `github` payload was inconsistent between push and pull-request.  At that point I figured I should just get it working.  
Pre-commit vomits all over my terminal repeatedly
This PR

MNT/STY/TST: Add pre-commit hooks, CI job, standardize style

---

scripts/serverStat

Trying to turn off or power cycle a drp node (a server with drp in its hostname) will instead point you to a confluence page explaining how to do this through the ipmi web interface and exit because using serverStat/psipmi sometimes causes the ipmi interfaces to stop working until they are manually restarted whereas the web interface works as exptected.
https://jira.slac.stanford.edu/browse/ECS-5126
Interactively
Code will print out a message, but I did not update the serverStat readme description because I thought this would be too specific to mention.

DEV: disabling serverstat off and cycle for drp nodes

---

scripts/get_info.py
scripts/restartdaq

- Hutch is determined by matching to subnets/hostname but `txiopr` currently uses `tmo-daq` or `rix-daq` machine to run. Other scripts depend on `txi` being correctly returned as the hutch from this script.
- TXI is temporarily running from tmo/rix machines. We need a mechanism
- Tested through local copies of relevant scripts in `txiopr/scripts`
Running local version (in `~txiopr/scripts`) of `restartdaq` as `txiopr`

MNT Temporarily modify `restartdaq` and `get_info` to allow TXI to run from TMO/RIX machines

---

scripts/dev_conda
scripts/pcds_conda

Remove opengl-related environment variable from the conda startup scripts
At LCLS, this was a temporary workaround that is causing a new issue.
- This variable is causing https://jira.slac.stanford.edu/browse/ECS-5700
- This variable was originally a workaround for https://jira.slac.stanford.edu/browse/ECS-1867, see https://jira.slac.stanford.edu/browse/ECS-1878, https://github.com/pcdshub/engineering_tools/pull/132, https://github.com/pcdshub/engineering_tools/pull/133
- Interactively, my applications no longer crash without this variable set: previously, even simply starting `pydm` would break everything.
- Now, sometimes I get a new OpenGL warning but no crashes.
In general, forcing the renderer settings in the conda environment sourceable led to a very confusing bug. This should have …

MAINT: remove glx env var, no longer needed and causing issues

---

README.md
scripts/afs-remote-fix
scripts/afs_remote_fix.py

Add `afs-remote-fix` (`afs_remote_fix.py`), a tiny script for changing a user's afs remote to point toward their fork and to pcdshub.
We're migrating the afs repos so this will be useful.
Interactively only
Here only in the readme and in the file

ENH: add quick script for repointing afs remotes to github

---

README.md
scripts/ioc-deploy
scripts/ioc_deploy.py

Create a (simplest possible?) ioc-deploy script for deploying IOCs from github to nfs. This would be a replacement for `epics-release` with the general goal of removing references to older version control systems and making the script easier to debug.
Here is the help text:
<details>
```
usage: ioc-deploy [-h] [--version] [--name NAME] [--release RELEASE]
[--ioc-dir IOC_DIR] [--github_org GITHUB_ORG]
[--auto-confirm] [--dry-run] [--verbose]
ioc-deploy is a script for building and deploying ioc tags from github. It
will create a shallow clone of your IOC in the standard release area at the
correct path and "make" it.
optional arguments:
-h, --help            show this help message and exit
--version             Show version number and exit.
--name NAME, -n NAME  The name of the repository …
```

ENH: add ioc-deploy script

---

scripts/ioc_deploy.py

Fix an issue where `ioc-deploy` would happily create new folders if you make a casing typo, e.g. `ioc-common-gigecam` will now deploy to `ioc/common/gigECam`.
Github URLs are case-insensitive, e.g. you can clone `ioc-coMMon-GiGeCaM` and it will work just fine.
So, we need to turn to other sources for the correct casing for directory deployment.
The REST API is the most consistent method, but it requires additional authentication.
This PR checks two things in order looking for a match:
- The existing deploy directories
- The README
https://jira.slac.stanford.edu/browse/ECS-6018
Interactively only, works as I expect
Here only

FIX: issues with ioc-deploy casing

---

scripts/ssh-agent-helper

Reviewers: I mostly want quick opinions about the word choice and the terminal output, you shouldn't spend a lot of time out of your day on this one. I think this is the normal/simplest way to check a return code in a bash script.
If the `ssh-add` step in `ssh-agent-helper` runs, let the user know how it goes.
The script remains silent if it didn't need to do anything.
This came up when @ljansen7 was deploying IOCs a week or so ago and the script output was unclear: did it work? Did it not work? Do I have to do it again?
Jira at https://jira.slac.stanford.edu/browse/ECS-6095
I ran the script a few times with different conditions:
Correct password:
```
zlentz@pslogin04:~$ source ~/github/engineering_tools/scripts/ssh-agent-helper
Starting ssh agent
Running ssh-add, may prompt for ssh key …
```

ENH: add messages for ssh-agent-helper exit state to make the result clear

---

scripts/ioc_deploy.py

This should be the second-to-last PR from me about this script from the Jira epic.
Main goal: make `ioc-deploy` succeed and fail faster, avoiding slow commands and long timeouts.
Main changes:
- Before a deploy action, `ping` github as a quick connectivity check.
- Check tags, auth, and repo availability all at once using `git ls-remote` one time instead of through multiple `git clone` commands.
- Rearrange logic in `get_deploy_info`, `finalize_name`, and `finalize_tag` to facilitate the above.
Incidental changes:
- Normalize `DeployInfo` to only use `str`, not `None` because it simplified some implementation details
- Rearrange some of the docstrings to match where code has moved
- Allow providing `--path-override` by itself during the deploy routines, which previously would error out. …

ENH: check for github early to avoid long timeouts, decrease usage of git clone

---

README.md
scripts/ioc_deploy.py

Main goal: allow us to make releases from the command line without going to the github website, for convenience
Main changes:
- If the provided release number does not exist, prompt the user to create a new tag.
- Enforce Rx.x.x format for the new tag
- The new tag is an annotated tag if we're adding a message to it, and a non-annotated tag otherwise
- Show the last commit message to the user for tag context, confirmation that they pushed their code, and as the defacto "default" message if they decide not to include one with their tag
Other things to note:
- Increase logging consistency between shell out functions
- Have a special message for `KeyboardInterrupt`, since it's way more likely to happen when the user is dropped into a text prompt, and seeing a traceback when you do it is a …

ENH: allow in-script tagging in ioc-deploy

---

scripts/ioc_deploy.py

In one of the ioc-deploy PRs we adjusted the cli arg specifics which made these docstrings incorrect.
This PR fixes a few minor docstrings that I noticed this morning.
Incorrect docs can be confusing
No functional changes to the code
Here only

DOC: minor docstring errors from renamed cli args

---

scripts/ipmConfigEpics

add xcs usrdio to ipmConfigEpics
xcs usrdio has to be add to ipmConfigEpics  to it can be used from the hutch engineering tools.

add xcs usrdio to ipmConfigEpics

---

scripts/daq_utils.py
scripts/daqutils
scripts/restartdaq
scripts/run_daq_utils.py
scripts/stopdaq
scripts/testdaqutils
scripts/wheredaq

- Procmgr is being replaced with slurm for some of the hutches. Daqmgr is the new utility for controlling DAQ slurm jobs. The changes here aim at overriding daq related commands such as restartdaq, stopdaq, etc for daqmgr hutches. These commands uses standard python that does not require sourcing prior to calling them. 
- The top part of daq-related scripts checks if the current hutch is daqmgr hutch and overrides the commands with the python modules added here. All the non daqmgr hutches continue to use existing shell scripts.
All slurm jobs launched by daqmgr are stored in slurm database. Daqutils added here is written in python to ease the job of reading of and parsing slurm job statuses. Some of these utilities are slimmed down version of what already exist in daqmgr making it easier …

use daqutils for daqmgr hutches

---

scripts/makepeds
scripts/makepeds_psana

Added the Alvium as a detector you could calibrate.
Should the queues be very busy, allow to add a reservation.
Check that the used account&reservation will work.
Quit when no files will be found after 5 mins waiting.
https://jira.slac.stanford.edu/browse/ECS-4364
https://jira.slac.stanford.edu/browse/ECS-6322
recreating pedestals for epix100, epix10k2m, jungfrau4M and check that it files for a non-existing run.

add alvium, reservation option &  some checks for permissions

---

scripts/daq_utils.py

The refactoring of call_subprocess missed stripping out leading and trailing whitespace. This caused get_info --gethutch called to return invalid hutch name. 
This is a new issue found after the software was deployed. Unfortunately, it was not caught earlier. Reason is unknown at the moment. 
A name-validation check using the string length for the hutches was added. This raises ValueError from daqutils inhibiting execution of the codes that follow.
Both tmo and rix have been tested.

Fix subprocess output not stripped

---

scripts/makepeds_psana

a hierarchical repo structure was deployed in S3DF. 
Fix to the report name when checking for membership.
a hierarchical repo structure was deployed in S3DF.  This makes my check if a given person is in the account they are using for batch submission fail, meaning the job run interactively and thus slower.
interactively on S3DF.
here.

hotfix for hierarchical repo structure

---

scripts/daq_utils.py

Adds `TXI` to the list of `DAQMGR_HUTCHES` so `restartdaq` will run the DAQ using SLURM for TXI from the `txi-daq` machine.
This normalizes the standard way of running the TXI DAQ to be the same as the other hutches.
Tested by starting the DAQ with paths in `restartdaq` modified to point to the modified file to ensure that the modified version is called. The specific changes (not included in the PR) are:
```diff
diff --git a/scripts/restartdaq b/scripts/restartdaq
index 5496162..bb6dd08 100755
--- a/scripts/restartdaq
+++ b/scripts/restartdaq
@@ -2,8 +2,8 @@
-if [ "$(daqutils isdaqmgr)" = "true" ]; then
-    daqutils $(basename "$0") $@
+if [ "$(/cds/home/opr/txiopr/scripts/engineering_tools/scripts/daqutils isdaqmgr)" = "true" ]; then
+ …
```

MNT Add TXI to DAQMGR_HUTCHES

---

README.md
scripts/daq_utils.py
scripts/restartdaq
scripts/run_daq_utils.py
scripts/startami
scripts/stopami

Adds a `--cnf` option to `run_daq_utils.py` which is passed to `daq_utils.DaqManager`. This allows us to indicate which cnf file to use for restarting/stopping the DAQ in LCLS2 hutches.
Currently, this is used for:
- Restarting AMI processes only in LCLS2 hutches instead of the entire DAQ, and the `startami` and `stopami` scripts have been updated accordingly. 
- Allowing for RIX to switch between QRIX and ChemRIX cnfs for `restartdaq`. `restartdaq -C <CNF>` will now work for LCLS2 hutches. `stopdaq` will still work as previously, assuming both CNFs have imported from the same "master/main" cnf.
*NOTE:* After this PR the `startami` and `stopami` scripts will perform the following depending on hutch:
- `startami`: Restart AMI1 in LCLS1 hutches AMI2 in LCLS2 hutches
- `stopami`: Stop AMI1 …

ENH Add option to specify CNF for LCLS2 hutches. Restart/stop AMI only for LCLS2 Hutches.

---

README.md
scripts/pgpwave8_upgrade
scripts/pgpwave8_upgrade.sh
scripts/pgpwave8_version.py

Adding a script to upgrade a pgpwave8. Provided the iocname and mcs file with the new firmware, it will find the lane, rogue version, host, ssh to the host, activate the corresponding rogue environment, and use wave8LoadFpga.py to upgrade the firmware. If the ioc is running, it will be deactivated and reactivated. It can also get the current firmware from either the ioc or a helper python script. 
I am currently using /cds/home/t/tjohnson/trunk/workarea/wave8, but this repo should be checked out in a common area. 
https://jira.slac.stanford.edu/browse/ECS-5609
I tested reading the version with and without the ioc enabled and upgrading the firmware on ioc-las-crix-pgpw8-03. I think Tyler Johnson should also try test this so someone from the laser group can confirm that it works as expected …

W8reprogram

---

scripts/startami

startami fails when trying to get a second client
Shell check forcing some changes that do not work. Revert and ignore shell check.
xpp-control as xppopr
N/A

BUG: fix second ami client start

---

scripts/grep_more_ioc
scripts/grep_more_ioc.py

Fixed some bugs in `grep_more_ioc` and added some QOL on the search sub-parsers. I'm probably the only person using this tool, but it makes life livable in `las` given the sheer number of IOCs.
Fixes #213 and #192 and improves functionality for piping output into other commands/scripts.
I have ran `../engineering_tools/grep_more_ioc` to use the changes in my fork and can successfully print all IOCs in all hutches, demonstrating #213 has fixed the issue I was seeing before when `Alias` procmngr keys included forbidden characters and digits that weren't being escaped correctly before reading the JSON.
I have also demonstrated that the new search subparser arguments work as expected:
This PR.
It is important to add that I have redefined what the `-o` optional flag for `search` does: …

grep_more_ioc improvements

---

scripts/restartdaq

`restartdaq` command did not function on UED machines as it would request a drp node which was an LCLS-II requirement with a network connection to the drp-network. UED has a stand-a-lone server (ued-cmp002) and no DRP-network. This has been fixed by checking the hostname for the string "ued" before executing a drp check. Similar code has been used in CXI.
DAQ has been restarted through ued-daq computer using the included version of `restartdaq` without issue on 26 November 2024. Tested separately by Ian Roque (iroque) and Patrick Oppermann (opperman).
Comments have been included in `restartdaq`.

drp node bypass for UED machines

---

README.md
scripts/startami2

Make a script to restart/stop ami2 and start more clients
Needed for smoother operation with ami2 in LCLS-I hutches
With XPP DAQ and AMI
N/A

ami2 script for lcls-1 hutches

---

scripts/takepeds

Change the environment that needs to be source (necessary due to split environment for LCLS2)
takepeds should work in UED
check that the executable can now be found.
here

Fix for UED takepeds

---

scripts/camViewer

add k-line camviewer config to K-line hutches
Also removed wait time functionality as the camviewer redesign changes how timeouts are handled.
make the txi camviewer work & keep the whole list of cameras for TMO & RIXS
due to TMo& RIXS including comon cameras explicitly, the TXI camviewer was not able to launch IM2K0 due to a found ambiguity
This request fixes this in a quick way.
Really, we should not look for cameras in _all_ config-files, but only the ones included for a given instruments avoiding potential duplicates if e.g. multiple hutch want to call a given camera e.g. SPEC.
I checked the list of available cameras from various instrument machines,

add k-line camviewer config to K-line hutches

---

scripts/makepeds
scripts/makepeds_psana

We now check the return code of the geometry & other constants deployment scripts
We should let the user now more explicitly when something goes wrong as expecting them to read through many lines of output....
I've tested this does not break anything, but the error scenario has been fixed in the meantime....

More error checking ^ reporting

---

scripts/makepeds_psana2

When you calculate pedestals, they should also be deployed 
use -o <CALIBDIR> command consistenly for both pedestal calculation& deployemnt!
see above. Affects UED only.

use output directory also for deploy step

---

scripts/restartdaq

Ued needs the option to switch between two cnf files.
That's why there is now -u with the options andor.cnf and epix.cnf.

add ued .cnf file

---

scripts/grep_more_ioc.py

Add the `-O, --no_filename` flag to the `search` subarg in `grep_more_ioc`. This, combined with some sneaky regex, can let you do some very useful automation for `caget` and `caput`-ing a batch of PVs.
In MODS there's often very many aliases for records and obscure PVs to check for device settings that can be laborious to compare and update. This helps streamline the process by giving an output that's easy to mangle with `xargs`. Take, for example, checking the temperature on all the Basler gigecams in the MODS:
```
~$ grep_more_ioc -d lm.k.*gige las search -qsnoO '^CAM_PV\s*\=\s*([_:\w]*)' |  xargs -I {} bas -c 'caget {}:TemperatureAbs_RBV'
LM1K2:COM_DP2_NF1:TemperatureAbs_RBV 46
LM1K2:EJX_DP2_FF1:TemperatureAbs_RBV 57
LM1K2:INJ_DP1_TF1_FF1:TemperatureAbs_RBV 57 …
```

Add --no_filename flag for search subarg in grep_more_ioc

---

.github/workflows/standard.yml

This version of the ubuntu runner image is being removed. We've chosen to go straight to `latest` everywhere to hopefully not need to manually switch it again.

MNT: switch off of deprecated os build and straight to latest

---

scripts/checkdaqroute
scripts/daq_utils.py
scripts/restartdaq
scripts/run_daq_utils.py
scripts/startami
scripts/stopami
scripts/stopdaq
scripts/wheredaq

This PR introduces a feature-rich update focused on improving reliability, maintainability, and clarity of the DAQ utility scripts. The core enhancements are:
- ✅ **Slurm command availability check**: Added checks for essential Slurm commands (`squeue`, `sbatch`, `scancel`) to ensure the host environment is valid before executing DAQ-related commands.
- **Unified command dispatch with `checkdaqroute`**: Introduced `checkdaqroute` as a central routing utility for bash scripts, streamlining command routing and reducing redundancy.
- 🔁 **Dynamic command dispatch**: Refactored DAQ command handling to use dynamic function lookup, reducing duplication and making it easier to extend or modify supported commands.
- 🧼 **Structured logging + better error handling**: Replaced `print` statements in …

Improve SLURM integration and command routing for daq utilities

---

.pre-commit-config.yaml
scripts/grep_more_ioc.py

Add a few new subargs for `print`:
* `-l, --list` for listing column parameters of the `dataframe`. e.g. `grep_more_ioc ctl-las-ip1-srv01 las print -l id`
* `-n, --no_dataframe` for if you _only_ want other printed subarg outputs. Skip printing the `dataframe`
* alphabetized subargs
Just some extra utility I've been running on my dev branch that might be useful in prod.
Been running this for a few weeks out of my dev branch, has been working just fine.
In this PR!

grep_more_ioc TLC

---

README.md
scripts/ioc_deploy.py

Add a `rebuild` command to `ioc-deploy`.
This will:
- strip any existing write permissions
- make
- apply write permissions
Which will be useful when trying to build a bunch of common IOCs on both rhel7 and rocky9.
I'm considering also adding a hosts argument to ioc-deploy to deploy to multiple architectures all at once, but I've deferred this because:
- The complexity of this "just one simple deploy script" is getting pretty high
- I didn't want to deal with auth error handling at EOD
Possibly the next update for `ioc-deploy` will bring it into an externally tracked module and then I can add complexity without causing issues in engineering_tools.
https://jira.slac.stanford.edu/browse/ECS-7695
>ioc-deploy works great but has some annoying behavior when you want to build on multiple …

ENH: ioc deploy rebuild

---

README.md
scripts/gige-vimba

`gige-vimba` simply opens a rhel7/rocky9-compatible vimba configuration gui from the vendor.
See https://www.alliedvision.com/en/products/vimba-sdk/
This is useful for setting up and debugging gige cameras from allied vision.
This has been sitting in my personal bin folder for a while but it shouldn't live there.
Interactively only.
In the README

ENH: add gige-vimba helper script for running the vimba software

---

scripts/makepeds_psana2

A change in the underlying code made a change in makepeds necessary - the log no longer ends in a line w/ DONE and we will use the return code exclusively to see if the jobs succeeded.

hot fix (pedestal processing for jungfrau in lcls2)

---

scripts/daq_utils.py
scripts/restartdaq
scripts/run_daq_utils.py

This PR restores the previously removed `-C`/`--cnf` configuration flag and adds support for a `-v`/`--verbose` flag for consistency across DAQ utilities. It also defers the config file existence check until the full path is available. Additionally, this update includes a workaround to suppress ShellCheck SC2034 warnings for unused variables `DAQMGR_CNF` and `VERBOSE`, which are required for compatibility with downstream tools.
These flags are necessary for proper argument parsing across multiple DAQ scripts. The missing `-C` option was causing failures when passing configuration files. The ShellCheck warnings were false positives—these variables are used indirectly via downstream utilities—so they are now referenced explicitly to keep pre-commit checks clean.
Tested manually by running …

Restore -C config flag and add -v; suppress ShellCheck warnings in restartdaq

---

README.md
scripts/condarc.yaml
scripts/dev_conda
scripts/pcds_conda
scripts/shared_conda_setup.sh

- Prepare for `pcds-6.0.0`, which will be python 3.12
- Clean up the duplicated code between `pcds_conda` and `dev_conda` and put it in a shared script.
- Add `dev-` to the conda prompt when using `dev_conda` (closes #202)
- Add variables that tell us which script we sourced for downstream consumers (like me in my crazy prompt) to use.
We're gearing up for an open beta release of `pcds-6.0.0` which will be python 3.12.
This update enables you to access that environment via:
```
export PCDS_CONDA_VER=6.0.0
source pcds_conda
```
Python 3.9 is still the default.
While I was here I remembered #202 and found a simple way to include it for normal users.
For users with custom prompts etc. like me I added two new exported variables to let us know you're using pcds conda or dev conda in case we …

ENH/MNT: updates/cleanups to conda setup scripts for py312

---

scripts/makepeds_psana2

Dettype for the axis cam at chemrixs has to be updated.
Tested for rix100836924 run 32
```
[opperman@sdfiana002 scripts]$ ./makepeds_psana2 -e rix100836924 -r 32 -q milano
XXXXXXXXXXXXXXXXX START MAKEPEDS at 09:33:16 on sdfiana002 XXXXXXXXXXXXXXXXXXXXXXXXXXXX
This is a LCLS-II experiment
Use XTC files from /sdf/data/lcls/ds/rix/rix100836924/xtc.
We will work from directory /sdf/data/lcls/ds/rix/rix100836924/results/calib_view/pedestal_workdir
Check for data files:
10
-r--r-----+ 1 psdatmgr ps-data      460970 May 18 21:24 /sdf/data/lcls/ds/rix/rix100836924/xtc/rix100836924-r0032-s008-c000.xtc2
-r--r-----+ 1 psdatmgr ps-data    16642696 May 18 21:24 /sdf/data/lcls/ds/rix/rix100836924/xtc/rix100836924-r0032-s009-c000.xtc2
-r--r-----+ 1 psdatmgr ps-data    89157461 May 18 21:24 …
```

fix for makepeds axis

---

scripts/makepeds_psana2

Added support in makepeds_psana for the MFX jungfrau16M: single processes need more memory and splitting this into the segments makes the job run faster. 
Also added a --noseg option to NOT split the jobs into segments.
The single jobs as defined before were killed as they exceeded the requested memory (8GB). This limit needed to be raised. As a second option, instead the job is split into the 0.5M segments to process more in parallel. This is a speedup of ~40%
I have also modified the epix-segment level processing for consistency
I've tested this on a MFX jungfrau run (mfx101332224, run 222) as well as UED run with the epix quad
here.

makepeds improvement for the jungfrau16M

---

scripts/makepeds_psana
scripts/makepeds_psana2
scripts/serverStat
scripts/stopdaq

This pull request contains mostly changes to the 'expert' option of serverStat. 
stopdaq had a few lines removed that were no longer necessary and makepeds_psana no longer requests 5 CPUs where 1 suffices.
Other minor changes to the information displayed have been added and three other minor changes to other script have been packaged
serverStat --expert
could lead to machines becoming unresponsive - which is not the expected behavior for a command that is simply supposed to show you some information about said server. The only recent change has been an update to the EDT code that was called to gain more information about those cards. Given that we have essentially discontinued the use of these cards, I have chosen to simple display that there _is_ one.
processed pedestals for the epixquad …

Server stat expert edt 

---

scripts/shared_conda_setup.sh

Our py 3.12 environment has been knocking around for a while now, it's time to make it the default environment. 
I also adjusted the "latest_env" file in the "py312" conda directory to contain "pcds-6.0.1"
I may have missed a file, but this worked well for me.
It's summer shutdown, and this is the least intrusive time to make this change.  (but on monday, no deployments on Friday)
I started a no-rc bash session and ran pcds_conda.  It successfully activated pcds-6.0.1
This PR

MNT: make pcds-6.0.1 the default conda environment

---

scripts/makepeds

This PR logs terminal output when running `makepeds` to a file in the operator home directory. Separately it addresses the spellcheck errors/warnings.
This PR is motivated to aid in debugging. Occassional issues with `makepeds` can be hard to debug. While logs are usually created on the S3DF-side, they can be hard to find. In the worst cases, not even these logs are available. This PR logs the terminal output that the operator sees to a file on the PCDS side to make debugging later easier.
Tested by making a small change (not in PR), so I don't have to mess with the operator environment.
```diff
diff --git a/scripts/makepeds b/scripts/makepeds
index e2c5d08..69a4e1c 100755
--- a/scripts/makepeds
+++ b/scripts/makepeds
@@ -1,6 +1,7 @@
#! /bin/bash
-DIR=$(dirname "$(readlink -f "$0")") …
```

ENH Log makepeds output to file. Spellcheck updates
